//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tapyt.Websites.Base.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbComment
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid EntryId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Text { get; set; }
        public int Upvote { get; set; }
        public int Downvote { get; set; }
    }
}
