//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tapyt.Websites.Base.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TapytEntities : DbContext
    {
        public TapytEntities()
            : base("name=TapytEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DbArea> DbArea { get; set; }
        public virtual DbSet<DbComment> DbComment { get; set; }
        public virtual DbSet<DbEntry> DbEntry { get; set; }
        public virtual DbSet<DbSubject> DbSubject { get; set; }
    }
}
